version: '3.8'

services:
  jupyter_app:
    build: .
    container_name: jupyter_data_pipeline
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  adminer:
    image: adminer
    container_name: adminer_db_tool
    ports:
      - "8080:8080"